version: '3.9'

x-common: &common
  image: $IMAGE_TAG
  secrets:
    - django_secret_key
    - postgres_password
    - minio_password
  env_file:
    - ../../envs/dev.env
  networks:
    - backend-net
  depends_on:
    - db
    - redis

services:
  backend:
    <<: *common
    command: ./start.sh
    ports:
      - "8000:8000"
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 10s
      retries: 20
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

  celery-worker:
    <<: *common
    command: ./start-celery-worker.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: sh -c 'celery -A config inspect ping'
      interval: 10s
      retries: 20

  celery-beat:
    <<: *common
    command: ./start-celery-beat.sh
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: sh -c 'celery -A config inspect ping'
      interval: 10s
      retries: 20

networks:
  backend-net:
    external: true

secrets:
  postgres_password:
    external: true
  django_secret_key:
    external: true
  minio_password:
    external: true
