version: '3.9'

services:
  db:
    image: postgres:16
    secrets:
      - postgres_password
    env_file:
      - ../../envs/dev.env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis
    env_file:
      - ../../envs/dev.env
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data/
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  redis_data:

networks:
  backend-net:
    external: true

secrets:
  postgres_password:
    external: true
  redis_password:
    external: true
