version: '3.9'

services:
  db:
    image: postgres:16
    secrets:
      - postgres_password
    env_file:
      - ../../envs/env.dev
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:

networks:
  backend-net:
    external: true

secrets:
  postgres_password:
    external: true
