version: '3.9'

x-common: &common
  image: $IMAGE_TAG
  secrets:
    - django_secret_key
    - postgres_password
  env_file:
    - ../../envs/env.prod
  networks:
    - backend-net
  depends_on:
    - db

services:
  backend:
    <<: *common
    command: ./start.sh
    ports:
      - "127.0.0.1:8000:8000"
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      replicas: 2 
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 30s  
        monitor: 60s  
      rollback_config:
        parallelism: 1
        order: start-first
        monitor: 30s
      restart_policy:
        condition: on-failure  
        delay: 10s  
        max_attempts: 5  
        window: 300s  
      placement:
        constraints:
          - node.role == worker
        preferences:
          - "spread=node.labels.zone"

networks:
  backend-net:
    external: true

secrets:
  postgres_password:
    external: true
  django_secret_key:
    external: true
