version: '3.9'

services:
  nginx:
    image: nginx:1.28.0-bookworm
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - nginx-conf:/etc/nginx/conf.d/
      # - nginx-certs:/etc/nginx/certs
    networks:
      - backend-net
    deploy:
      replicas: 2  # Multiple nginx instances for production
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.2'
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 300s
      placement:
        constraints:
          - node.role == worker
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
      - source: nginx_main_conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - app

configs:
  nginx_conf:
    file: ../../conf/nginx/prod/conf.d/default.conf
  nginx_main_conf:
    file: ../../conf/nginx/prod/nginx.conf

volumes:
  nginx-conf:
    external: true
  nginx-certs:
    external: true

networks:
  backend-net:
    external: true
