# Generated by Django 5.2.3 on 2025-12-24 19:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=200, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('resource_type', models.CharField(max_length=100, verbose_name='resource type')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('list', 'List')], max_length=50, verbose_name='action')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['code'], name='permissions_code_a0a529_idx'), models.Index(fields=['resource_type'], name='permissions_resourc_e96609_idx'), models.Index(fields=['action'], name='permissions_action_208379_idx'), models.Index(fields=['resource_type', 'action'], name='permissions_resourc_f080ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_system', models.BooleanField(default=False, verbose_name='system role')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'indexes': [models.Index(fields=['name'], name='roles_name_a96913_idx'), models.Index(fields=['is_system'], name='roles_is_syst_8ea1ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('resource_type', models.CharField(max_length=100, verbose_name='resource type')),
                ('resource_id', models.PositiveIntegerField(verbose_name='resource id')),
                ('is_granted', models.BooleanField(default=True, verbose_name='is granted')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='granted at')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_object_permissions', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_object_permissions', to='accounts.permission', verbose_name='permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_object_permissions', to='accounts.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'role object permission',
                'verbose_name_plural': 'role object permissions',
                'db_table': 'role_object_permissions',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission', verbose_name='permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
                'db_table': 'role_permissions',
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('token_jti', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='token jti')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='blacklisted at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'token blacklist',
                'verbose_name_plural': 'token blacklist',
                'db_table': 'token_blacklist',
            },
        ),
        migrations.CreateModel(
            name='UserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('resource_type', models.CharField(max_length=100, verbose_name='resource type')),
                ('resource_id', models.PositiveIntegerField(verbose_name='resource id')),
                ('is_granted', models.BooleanField(default=True, verbose_name='is granted')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='granted at')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_user_object_permissions', to=settings.AUTH_USER_MODEL, verbose_name='granted by')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to='accounts.permission', verbose_name='permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_object_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user object permission',
                'verbose_name_plural': 'user object permissions',
                'db_table': 'user_object_permissions',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='assigned at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='assigned by')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.role', verbose_name='role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user role',
                'verbose_name_plural': 'user roles',
                'db_table': 'user_roles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='users_deleted_e48316_idx'),
        ),
        migrations.AddIndex(
            model_name='roleobjectpermission',
            index=models.Index(fields=['role', 'resource_type', 'resource_id'], name='role_object_role_id_9304d5_idx'),
        ),
        migrations.AddIndex(
            model_name='roleobjectpermission',
            index=models.Index(fields=['role', 'is_granted'], name='role_object_role_id_ddd265_idx'),
        ),
        migrations.AddIndex(
            model_name='roleobjectpermission',
            index=models.Index(fields=['resource_type', 'resource_id'], name='role_object_resourc_53d9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='roleobjectpermission',
            index=models.Index(fields=['granted_at'], name='role_object_granted_e6b06f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleobjectpermission',
            unique_together={('role', 'permission', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='role_permis_role_id_29a93b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['token_jti'], name='token_black_token_j_9016ba_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['user'], name='token_black_user_id_444aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenblacklist',
            index=models.Index(fields=['expires_at'], name='token_black_expires_07a99b_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(fields=['user', 'resource_type', 'resource_id'], name='user_object_user_id_1ae0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(fields=['user', 'is_granted'], name='user_object_user_id_634551_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(fields=['resource_type', 'resource_id'], name='user_object_resourc_83d5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userobjectpermission',
            index=models.Index(fields=['granted_at'], name='user_object_granted_2d45c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userobjectpermission',
            unique_together={('user', 'permission', 'resource_type', 'resource_id')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='user_roles_user_id_801a9e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['assigned_at'], name='user_roles_assigne_f2447a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
